[project]
name = 'sft-basic'
description = ''
authors = []
telemetry = false
cache_dir = '.\.cache'
requirements = []

[contracts.semi-fungible-token]
path = 'contracts/semi-fungible-token.clar'
clarity_version = 1
epoch = 2.0

[contracts.sip013-semi-fungible-token-trait]
path = 'contracts/sip013-semi-fungible-token-trait.clar'
clarity_version = 1
epoch = 2.0

[contracts.sip013-transfer-many-trait]
path = 'contracts/sip013-transfer-many-trait.clar'
clarity_version = 1
epoch = 2.0
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
