[project]
name = 'sfts-advanced'
description = ''
authors = []
telemetry = false
cache_dir = '.\.cache'
requirements = []
[contracts.collection-1]
path = 'contracts/collection-1.clar'
clarity_version = 1
epoch = 2.0

[contracts.items]
path = 'contracts/items.clar'
clarity_version = 1
epoch = 2.0

[contracts.main-sc]
path = 'contracts/main-sc.clar'
clarity_version = 1
epoch = 2.0

[contracts.resources]
path = 'contracts/resources.clar'
clarity_version = 1
epoch = 2.0

[contracts.sip013-semi-fungible-token-trait]
path = 'contracts/sip013-semi-fungible-token-trait.clar'
clarity_version = 1
epoch = 2.0

[contracts.sip013-transfer-many-trait]
path = 'contracts/sip013-transfer-many-trait.clar'
clarity_version = 1
epoch = 2.0
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
